language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
install: 
    - "pip install ."
    - "pip install -r requirements/test_requirements.txt"
script:
    - "nosetests --with-coverage --cover-package=mdx_subscript"
after_success:
    - "coveralls"
